[package]
name = "bpm"
version = "0.1.0"
authors = ["Antti Ala-Ilkka <antti@instereo.fi>"]
edition = "2018"

[dependencies]
lazy_static = "1.5"
parking_lot = "0.12.3"
chrono = "0.4.41"

[lib]
crate-type = ["cdylib"]